from enum import Enum

from hardware.display_platforms import Pmic


class Max17135(Pmic):
    # HVPMIC MAX17135 timings for Type4 Display (Maxim Drivers)
    HVPMIC_NB_TIMINGS=8
    HVPMIC_TIMING_SEQ0_UP_VGNEG=24
    HVPMIC_TIMING_SEQ0_UP_VSNEG =7
    HVPMIC_TIMING_SEQ0_UP_VSPOS =2
    HVPMIC_TIMING_SEQ0_UP_VGPOS= 12
    HVPMIC_TIMING_SEQ0_DOWN_VGPOS= 7
    HVPMIC_TIMING_SEQ0_DOWN_VSPOS =14
    HVPMIC_TIMING_SEQ0_DOWN_VSNEG =12
    HVPMIC_TIMING_SEQ0_DOWN_VGNEG =2

    # HVPMIC MAX17135 timings for Type11 Display (ST Drivers)
    HVPMIC_TIMING_SEQ1_UP_VGNEG=12
    HVPMIC_TIMING_SEQ1_UP_VSNEG= 7
    HVPMIC_TIMING_SEQ1_UP_VSPOS= 2
    HVPMIC_TIMING_SEQ1_UP_VGPOS= 23
    HVPMIC_TIMING_SEQ1_DOWN_VGPOS=2
    HVPMIC_TIMING_SEQ1_DOWN_VSPOS=14
    HVPMIC_TIMING_SEQ1_DOWN_VSNEG=12
    HVPMIC_TIMING_SEQ1_DOWN_VGNEG=7

    class Register(Enum):
       HVPMIC_REG_EXT_TEMP = 0x00
       HVPMIC_REG_CONF = 0x01
       HVPMIC_REG_INT_TEMP = 0x04
       HVPMIC_REG_TEMP_STAT = 0x05
       HVPMIC_REG_PROD_REV = 0x06
       HVPMIC_REG_PROD_ID = 0x07
       HVPMIC_REG_DVR = 0x08
       HVPMIC_REG_ENABLE = 0x09
       HVPMIC_REG_FAULT = 0x0A
       HVPMIC_REG_PROG = 0x0C
       HVPMIC_REG_TIMING_1 = 0x10
       HVPMIC_REG_TIMING_2 = 0x11
       HVPMIC_REG_TIMING_3 = 0x12
       HVPMIC_REG_TIMING_4 = 0x13
       HVPMIC_REG_TIMING_5 = 0x14
       HVPMIC_REG_TIMING_6 = 0x15
       HVPMIC_REG_TIMING_7 = 0x16
       HVPMIC_REG_TIMING_8 = 0x17

    def __init__(self, i2c_id, i2c_addr):
        super().__init__(i2c_id=i2c_id, i2c_addr=i2c_addr)



